# Generated by Django 4.1.3 on 2023-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplieduser',
            name='submit_resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
