# Generated by Django 4.1.3 on 2023-09-04 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_feed', '0002_joblisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='applied_user',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='JobAppliedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(default='hold', max_length=100)),
                ('applied_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app_feed.joblisting')),
            ],
        ),
    ]
