# Generated by Django 4.1.3 on 2023-09-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_feed', '0005_alter_jobapplieduser_applied_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplieduser',
            name='applied_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joblisting', to=settings.AUTH_USER_MODEL),
        ),
    ]
