# Generated by Django 4.1.3 on 2023-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='about_company',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
